<#
.SYNOPSIS
    Build evidence pack from Promptfoo results

.DESCRIPTION
    Collects evaluation results into timestamped evidence pack
    suitable for audit/ATO reviews.

.PARAMETER GitCommit
    Git commit SHA (default: current HEAD)

.PARAMETER EnvironmentName
    Environment name (default: "unknown")

.EXAMPLE
    .\build-evidence-pack.ps1

.EXAMPLE
    .\build-evidence-pack.ps1 -GitCommit "abc123" -EnvironmentName "production"

.NOTES
    Last Updated: 2026-02-17
#>

param(
    [Parameter()]
    [string]$GitCommit = "",

    [Parameter()]
    [string]$EnvironmentName = "unknown"
)

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Split-Path -Parent $scriptDir

Write-Host "=== EVA Evidence Pack Builder ===" -ForegroundColor Cyan

# Generate pack ID (timestamp)
$packId = Get-Date -Format "yyyyMMddTHHmmssZ"
$outputDir = Join-Path $projectRoot "docs\evidence-pack\output\$packId"

Write-Host "Pack ID: $packId" -ForegroundColor Green
Write-Host "Output Directory: $outputDir" -ForegroundColor Gray

# Create output directory
New-Item -ItemType Directory -Force -Path $outputDir | Out-Null

# Get Git commit
if (-not $GitCommit) {
    try {
        $GitCommit = git rev-parse HEAD
    }
    catch {
        $GitCommit = "unknown"
    }
}

# Collect results
$resultsDir = Join-Path $projectRoot "eval\promptfoo\results"
$suiteResults = @{}

if (Test-Path $resultsDir) {
    Get-ChildItem -Path $resultsDir -Filter "*-output.json" | ForEach-Object {
        $suiteName = $_.BaseName -replace "-output$", ""
        $resultData = Get-Content $_.FullName | ConvertFrom-Json

        $passed = ($resultData.results | Where-Object { $_.pass }).Count
        $failed = ($resultData.results | Where-Object { -not $_.pass }).Count
        $total = $resultData.results.Count

        $suiteResults[$suiteName] = @{
            total = $total
            passed = $passed
            failed = $failed
        }

        # Copy result file
        Copy-Item $_.FullName (Join-Path $outputDir "$suiteName-results.json")
        Write-Host "✓ Collected $suiteName results" -ForegroundColor Green
    }
}

# Calculate overall stats
$overallTotal = ($suiteResults.Values | Measure-Object -Property total -Sum).Sum
$overallPassed = ($suiteResults.Values | Measure-Object -Property passed -Sum).Sum
$overallFailed = ($suiteResults.Values | Measure-Object -Property failed -Sum).Sum
$passRate = if ($overallTotal -gt 0) { [math]::Round(($overallPassed / $overallTotal), 4) } else { 0 }

# Build manifest
$manifest = @{
    pack_id = $packId
    generated_at = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
    environment = $EnvironmentName
    backend_version = "unknown"  # TODO: Extract from backend
    git_commit = $GitCommit
    suites = $suiteResults
    overall_pass_rate = $passRate
    blocking_failures = $overallFailed
    evidence_files = @($suiteResults.Keys | ForEach-Object { "$_-results.json" })
}

# Write manifest
$manifestPath = Join-Path $outputDir "manifest.json"
$manifest | ConvertTo-Json -Depth 10 | Set-Content $manifestPath
Write-Host "✓ Generated manifest.json" -ForegroundColor Green

# Generate README
$readmePath = Join-Path $outputDir "README.md"
$readmeContent = @"
# Evidence Pack: $packId

**Generated:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss UTC")  
**Environment:** $EnvironmentName  
**Git Commit:** $GitCommit  

## Summary

- **Total Tests:** $overallTotal
- **Passed:** $overallPassed
- **Failed:** $overallFailed
- **Pass Rate:** $($passRate * 100)%

## Suites

$(foreach ($suite in $suiteResults.Keys) {
    $result = $suiteResults[$suite]
    "- **$suite**: $($result.passed)/$($result.total) passed"
})

## Files

$(foreach ($file in $manifest.evidence_files) {
    "- [$file](./$file)"
})

---

**Generated by:** EVA Red Team Harness  
**Version:** 1.0.0
"@

$readmeContent | Set-Content $readmePath
Write-Host "✓ Generated README.md" -ForegroundColor Green

# Summary
Write-Host "`n===================================================" -ForegroundColor Cyan
Write-Host "Evidence pack created successfully!" -ForegroundColor Green
Write-Host "Location: $outputDir" -ForegroundColor Cyan
Write-Host "Pass Rate: $($passRate * 100)%" -ForegroundColor $(if ($passRate -ge 0.9) { "Green" } elseif ($passRate -ge 0.75) { "Yellow" } else { "Red" })
Write-Host "===================================================" -ForegroundColor Cyan
